### ISSUE TITLE
how to run it？Check point file is streaming wrong

### ISSUE THREAD

**Issue by blowsummer** [FinnBehrendt/node21-submit#2]
MacBook-Pro node21-submit % docker run -it --rm --platform linux/amd64 your_image_name /bin/bash

parameters are /bin/bash
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: (30 second timeout) 
wandb: W&B disabled due to login timeout.
wandb: WARNING Path /opt/algorithm/wandb/ wasn't writable, using system temp directory
usage: process.py [-h] [--train] [--retrain] [--retest] input_dir output_dir
process.py: error: unrecognized arguments: /bin/bash
I keep reporting errors when I try to run your code with docker. Could you please provide a teaching video of how your code runs.

**Comment by FinnBehrendt** [comment]
Hi, 
Unfortunately, I do not have the time to create a teaching video for this repository. 
To build and test the docker, you can run the build.sh and test.sh bash scripts. Have you tried that?
Best regards
Finn
